root: true
env:
  browser: true
  es6: true
  node: true
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
parserOptions:
  ecmaVersion: 10
  sourceType: module
  ecmaFeatures:
    experimentalObjectRestSpread: true
rules:
  '@typescript-eslint/ban-ts-comment': 2
  '@typescript-eslint/no-unused-vars':
    - 2
    - ignoreRestSiblings: true
  '@typescript-eslint/type-annotation-spacing': 2
  '@typescript-eslint/no-extra-non-null-assertion': 2
  '@typescript-eslint/indent':
    - 2
    - 2
    - SwitchCase: 1
  '@typescript-eslint/member-delimiter-style': 2
  '@typescript-eslint/semi': 2
  '@typescript-eslint/space-before-function-paren': 2
  '@typescript-eslint/no-use-before-define': 2
  '@typescript-eslint/no-extra-parens': # 禁止不必要的括号
    - 2
    - all
    - ignoreJSX: all
  no-undef: 2
  no-undefined: 2
  for-direction: 2 # 强制 “for” 循环中更新子句的计数器朝着正确的方向移动
  getter-return: 2 # 强制 "getter" 函数中出现 "return" 语句
  # no-await-in-loop: 2 # 禁止在循环中出现 await
  no-compare-neg-zero: 2 # 禁止与 -0 进行比较
  no-cond-assign: 2 # 禁止条件表达式中出现赋值操作符
  no-console: 1 # 禁用 console
  no-constant-condition: 2 # 禁止在条件中使用常量表达式
  no-control-regex: 2 #禁止在正则表达式中使用控制字符
  no-debugger: 2 # 禁用 debugger
  no-dupe-args: 2 # 禁止 function 定义中出现重名参数
  no-dupe-keys: 2 # 禁止对象字面量中出现重复的 key
  no-duplicate-case: 2 # 禁止出现重复的 case 标签
  no-empty: # 禁止出现空语句块
    - 2
    - allowEmptyCatch: true
  no-ex-assign: 2 # 禁止对 catch 子句的参数重新赋值
  no-extra-boolean-cast: 2 # 禁止不必要的布尔转换
  no-extra-semi: 2 # 禁止不必要的分号
  no-func-assign: 2 # 禁止对 function 声明重新赋值
  no-inner-declarations: 2 # 禁止在嵌套的块中出现变量声明或 function 声明
  no-invalid-regexp: 2 # 禁止 RegExp 构造函数中存在无效的正则表达式字符串
  no-irregular-whitespace: 2 # 禁止在字符串和注释之外不规则的空白
  no-obj-calls: 2 # 禁止把全局对象作为函数调用
  no-prototype-builtins: 2 # 禁止直接调用 Object.prototypes 的内置属性
  no-regex-spaces: 2 # 禁止正则表达式字面量中出现多个空格
  no-sparse-arrays: 2 # 禁用稀疏数组
  no-template-curly-in-string: 2 # 禁止在常规字符串中出现模板字面量占位符语法
  no-unexpected-multiline: 2 # 禁止出现令人困惑的多行表达式
  no-unreachable: 2  # 禁止在return、throw、continue 和 break 语句之后出现不可达代码
  no-unsafe-finally: 2 # 禁止在 finally 语句块中出现控制流语句
  no-unsafe-negation: 2 # 禁止对关系运算符的左操作数使用否定操作符
  use-isnan: 2 # 要求使用 isNaN() 检查 NaN
  # valid-jsdoc: 2 # 强制使用有效的 JSDoc 注释
  valid-typeof: 2 # 强制 typeof 表达式与有效的字符串进行比较
  accessor-pairs: 2 # 强制 getter 和 setter 在对象中成对出现
  array-callback-return: 2 # 强制数组方法的回调函数中有 return 语句
  block-scoped-var: 2 # 强制把变量的使用限制在其定义的作用域范围内
  consistent-return: 0 # 要求 return 语句要么总是指定返回的值，要么不指定
  curly: # 强制所有控制语句使用一致的括号风格
    - 2
    - all
  default-case: 0 # 要求 switch 语句中有 default 分支
  dot-location:
    - 2 # 强制在点号之前和之后一致的换行
    - property
  eqeqeq: 2 # 要求使用 === 和 !==
  no-alert: 2
  no-caller: 2
  no-else-return: 2 # 禁止 if 语句中 return 语句之后有 else 块
  no-empty-function: 2 # 禁止出现空函数
  no-empty-pattern: 2 # 禁止使用空解构模式
  no-eq-null: 2 # 禁止在没有类型检查操作符的情况下与 null 进行比较
  no-eval: 2
  no-extend-native: 2 # 禁止扩展原生类型
  no-extra-bind: 2 # 禁止不必要的 .bind() 调用
  no-extra-label: 2 # 禁用不必要的标签
  no-fallthrough: 2 # 禁止 case 语句落空
  no-floating-decimal: 2 # 禁止数字字面量中使用前导和末尾小数点
  no-global-assign: 2 # 禁止对原生对象或只读的全局对象进行赋值
  no-implied-eval: 2 # 禁止使用类似 eval() 的方法
  no-iterator: 2 # 禁用 __iterator__ 属性
  no-labels: 2 # 禁用标签语句
  no-lone-blocks: 2 # 禁用不必要的嵌套块
  no-loop-func: 2 # 禁止在循环中出现 function 声明和表达式
  no-multi-spaces: 2 # 禁止使用多个空格
  no-multi-str: 2 # 禁止使用多行字符串
  no-new-func: 2 # 禁止对 Function 对象使用 new 操作符
  no-new-wrappers: 2 # 禁止对 String，Number 和 Boolean 使用 new 操作符
  no-octal: 2 # 禁用八进制字面量
  no-octal-escape: 2 # 禁止在字符串中使用八进制转义序列
  no-proto: 2 # 禁用 __proto__ 属性
  no-redeclare: 2 # 禁止多次声明同一变量
  no-return-await: 2 # 禁用不必要的 return await
  no-script-url: 2 # 禁止使用 javascript: url
  no-self-assign: 2 # 禁止自我赋值
  no-self-compare: 2 # 禁止自身比较
  no-sequences: 2 # 禁用逗号操作符
  no-throw-literal: 2 # 禁止抛出异常字面量
  no-unmodified-loop-condition: 2 # 禁用一成不变的循环条件
  no-unused-labels: 2 #禁用出现未使用过的标
  no-useless-call: 2 # 禁止不必要的 .call() 和 .apply()
  no-useless-concat: 2 # 禁止不必要的字符串字面量或模板字面量的连接
  no-useless-escape: 2 # 禁用不必要的转义字符
  no-useless-return: 2 # 禁止多余的 return 语句
  no-with: 2
  radix: 2 # 强制在parseInt()使用基数参数
  require-await: 2 # 禁止使用不带 await 表达式的 async 函数
  vars-on-top: 2 # 要求所有的 var 声明出现在它们所在的作用域顶部
  wrap-iife: 2 # 要求 IIFE 使用括号括起来
  yoda: # 判断常量在前
    - 2
    - never
    - onlyEquality: true
  no-delete-var: 2
  #  格式   #
  # array-bracket-newline:
  #   - 2
  #   - multiline: true
  array-bracket-spacing:
    - 2
    - never
  # array-element-newline:
  #   - 2
  #   - multiline: true
  block-spacing:
    - 2
    - always
  brace-style:
    - 2
    - 1tbs
  camelcase:
    - 2
    # - allow:
  comma-dangle:
    - 2
    - always-multiline
  comma-spacing: 2
  comma-style: 2
  computed-property-spacing: 2
  eol-last: 2
  func-call-spacing: 2
  func-name-matching:
    - 2
    - always
    - includeCommonJSModuleExports: true
  func-style:
    - 2
    - declaration
    - allowArrowFunctions: true
  function-paren-newline:
    - 2
    - multiline
  jsx-quotes: 2
  key-spacing: 2
  keyword-spacing: 2
  new-cap: 2
  new-parens: 2
  no-array-constructor: 2
  # no-continue: 2
  no-lonely-if: 2
  no-multi-assign: 2
  no-multiple-empty-lines:
    - 2
    - max: 1
  no-new-object: 2
  no-tabs: 2
  no-trailing-spaces: 2
  no-unneeded-ternary: 2
  no-whitespace-before-property: 2
  object-curly-newline: 2
  object-curly-spacing:
    - 2
    - always
    - arraysInObjects: false
  one-var-declaration-per-line: 2
  operator-assignment: 2
  operator-linebreak: 2
  padded-blocks:
    - 2
    - never
  quote-props:
    - 2
    - as-needed
  quotes:
    - 2
    - single
    - allowTemplateLiterals: true
  semi-spacing: 2
  semi-style: 2
  space-before-blocks: 2
  space-in-parens: 2
  space-infix-ops: 2
  space-unary-ops: 2
  switch-colon-spacing: 2
  template-tag-spacing: 2
  arrow-body-style: 2
  arrow-parens:
    - 2
    - as-needed
  arrow-spacing: 2
  constructor-super: 2
  generator-star-spacing: 2
  no-class-assign: 2
  no-const-assign: 2
  no-duplicate-imports: 2
  no-new-symbol: 2
  no-this-before-super: 2
  no-useless-computed-key: 2
  no-useless-constructor: 2
  no-useless-rename: 2
  no-var: 2
  object-shorthand: 2
  prefer-arrow-callback: 2
  prefer-const: 2
  prefer-numeric-literals: 2
  prefer-rest-params: 2
  prefer-spread: 2
  prefer-template: 2
  rest-spread-spacing:
    - 2
    - never
  require-yield: 2
  symbol-description: 2
  template-curly-spacing: 2
  yield-star-spacing: 2
  no-native-reassign: 2